logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    enableLoggingRequestDetails: False
    com.apcbc.cs411backend: DEBUG

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL:34.70.101.192}:3306/dev
    username: ${DATABASE_USERNAME:jinheng2}
    password: ${DATABASE_PASSWORD:Lgh147258}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never
      schema-locations: "classpath:database-init.sql"

server:
  error:
    include-message: always